version: '3.7'
 
services:
  db:
    image: postgres:16.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=pw"
      - "POSTGRES_DB=nesttest"
      - "TZ=Asia/Seoul"
    networks:
      - dbcon

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:pw@host.docker.internal:5432/nesttest?schema=public
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
    networks:
      - dbcon
    command: ["bash", "-c", "npx prisma db push && yarn start:dev"]

networks:
  dbcon:
      driver: bridge
  